version: '3.8'

services:
  # Serviço para o PostgreSQL
  db:
    image: postgres:latest
    environment:
      POSTGRES_DB: sggh_teacher
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: admin123
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./sql:/docker-entrypoint-initdb.d
    networks:
      - gradeHoraria

  # Serviço para a aplicação Spring Boot
  app:
    build: 
      context: .
      dockerfile: Dockerfile
    ports:
      - "8081:8081"
    depends_on:
      - db
      - keycloak
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://db:5432/sggh_teacher
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: admin123
      SPRING_FLYWAY_LOCATIONS: classpath:db/migration
      SPRING_SECURITY_OAUTH2_RESOURCESERVER_JWT_ISSUER_URI: http://keycloak:8080/realms/gradeHoraria
      SPRING_SECURITY_OAUTH2_RESOURCESERVER_JWT_JWK_SET_URI: http://keycloak:8080/realms/gradeHoraria/protocol/openid-connect/certs
    networks:
      - gradeHoraria

  keycloak:
    image: quay.io/keycloak/keycloak:23.0.7
    ports:
      - "8080:8080"
    environment:
      - KEYCLOAK_ADMIN=admin
      - KEYCLOAK_ADMIN_PASSWORD=admin
    command: start-dev
    networks:
      - gradeHoraria

networks:
  gradeHoraria:
    driver: bridge
      
volumes:
  postgres_data:
